import type { FAQ, Product, Service, Testimonial } from './types';

const pexels = 'https://images.pexels.com/photos';

export const products: Product[] = [
  {
    id: 'minimalist-sculpture',
    name: 'Minimalist Sculpture',
    description: 'A fluid, gallery-worthy form made to make quiet spaces feel intentional.',
    category: 'Home',
    price: 39.99,
    images: [
      `${pexels}/11134290/pexels-photo-11134290.jpeg?auto=compress&cs=tinysrgb&w=900`,
      `${pexels}/10726947/pexels-photo-10726947.jpeg?auto=compress&cs=tinysrgb&w=900`,
    ],
    rating: 4.9,
    reviews: 124,
    dimensions: '22 × 10 × 8 cm',
    colors: ['Ivory', 'Sand', 'Charcoal'],
    sizes: [],
    stock: 12,
    featured: true,
  },
  {
    id: 'multi-face-bust',
    name: 'Multi-Face Bust',
    description: 'An expressive statement piece printed with layered matte detail.',
    category: 'Home',
    price: 54.99,
    images: [
      `${pexels}/14608172/pexels-photo-14608172.jpeg?auto=compress&cs=tinysrgb&w=900`,
      `${pexels}/15979606/pexels-photo-15979606.jpeg?auto=compress&cs=tinysrgb&w=900`,
    ],
    rating: 4.8,
    reviews: 86,
    dimensions: '26 × 15 × 13 cm',
    colors: ['Charcoal', 'Stone'],
    sizes: [],
    stock: 7,
    featured: true,
  },
  {
    id: 'cosmetic-organizer',
    name: '3D Makeup Organizer',
    description: 'Custom-designed desktop makeup organizer with brush and palette slots.',
    category: 'Makeup',
    price: 28.5,
    images: [`${pexels}/15979598/pexels-photo-15979598.jpeg?auto=compress&cs=tinysrgb&w=900`],
    rating: 5,
    reviews: 41,
    dimensions: '20 × 14 × 10 cm',
    colors: ['White', 'Pastel Pink', 'Marble'],
    sizes: [],
    stock: 15,
    featured: true,
  },
  {
    id: 'anatomical-spine-model',
    name: 'Anatomical Medical Model',
    description: 'High-precision 3D printed educational anatomical model for clinics and offices.',
    category: 'Doctors',
    price: 89.99,
    images: [`${pexels}/16307279/pexels-photo-16307279.jpeg?auto=compress&cs=tinysrgb&w=900`],
    rating: 4.9,
    reviews: 33,
    dimensions: '30 × 12 × 12 cm',
    colors: ['Medical Bone', 'White'],
    sizes: [],
    stock: 8,
    featured: true,
  },
  {
    id: 'custom-car-keychain-gauge',
    name: 'Custom Car Emblem & Keychain',
    description: 'Durable heat-resistant filament badge and custom interior dashboard accessories.',
    category: 'Cars',
    price: 19.99,
    images: [`${pexels}/38873706/pexels-photo-38873706.jpeg?auto=compress&cs=tinysrgb&w=900`],
    rating: 4.7,
    reviews: 72,
    dimensions: 'Custom fit',
    colors: ['Matte Black', 'Carbon Gray'],
    sizes: [],
    stock: 30,
    featured: true,
  },
  {
    id: 'dental-display-teeth',
    name: 'Dental Desk Display',
    description: 'Detailed dental jaw model ideal for clinics and patient consultations.',
    category: 'Doctors',
    price: 45.0,
    images: [`${pexels}/14608172/pexels-photo-14608172.jpeg?auto=compress&cs=tinysrgb&w=900`],
    rating: 4.8,
    reviews: 55,
    dimensions: '10 × 8 × 7 cm',
    colors: ['Ivory'],
    sizes: [],
    stock: 21,
  },
  {
    id: 'geometric-planter',
    name: 'Geometric Home Planter',
    description: 'Modern desktop plant holder printed with biodegradable filament.',
    category: 'Home',
    price: 18.0,
    images: [`${pexels}/10726947/pexels-photo-10726947.jpeg?auto=compress&cs=tinysrgb&w=900`],
    rating: 4.6,
    reviews: 68,
    dimensions: '12 × 12 × 11 cm',
    colors: ['Terracotta', 'Sage Green', 'White'],
    sizes: [],
    stock: 40,
  },
  {
    id: 'car-phone-mount-adapter',
    name: 'Custom Vent Phone Mount',
    description: 'Precision-measured vent adapter engineered specifically for custom car interiors.',
    category: 'Cars',
    price: 22.5,
    images: [`${pexels}/11134290/pexels-photo-11134290.jpeg?auto=compress&cs=tinysrgb&w=900`],
    rating: 4.8,
    reviews: 29,
    dimensions: 'Custom fit',
    colors: ['Black'],
    sizes: [],
    stock: 25,
  },
  {
    id: 'phone-stand-pro',
    name: 'Ergonomic Phone Stand',
    description: 'A sleek, 3D-printed desktop phone stand designed for optimal viewing angles.',
    category: 'Phone Accessories',
    price: 15.99,
    images: [`https://images.pexels.com/photos/11134290/pexels-photo-11134290.jpeg?auto=compress&cs=tinysrgb&w=900`],
    rating: 4.9,
    reviews: 45,
    dimensions: '10 × 8 × 9 cm',
    colors: ['Matte Black', 'Silver', 'White'],
    sizes: [],
    stock: 20,
    featured: true,
  },
  {
    id: 'modern-kitchen-organizer',
    name: 'Modular Spice & Utensil Holder',
    description: 'Keep your kitchen counters neat with a custom-designed 3D-printed organizer.',
    category: 'Kitchen',
    price: 32.0,
    images: [`https://images.pexels.com/photos/10726947/pexels-photo-10726947.jpeg?auto=compress&cs=tinysrgb&w=900`],
    rating: 4.8,
    reviews: 38,
    dimensions: '25 × 12 × 10 cm',
    colors: ['White', 'Slate Gray', 'Beige'],
    sizes: [],
    stock: 18,
    featured: true,
  },
];

export const categories = ['All', 'Home', 'Makeup', 'Doctors', 'Cars', 'Phone Accessories', 'Kitchen'] as const;

export const services: Service[] = [
  { 
    title: 'Custom 3D Printing',
    description: 'Bring your 3D model, sketch, or design idea. We print it with high accuracy.',
    icon: 'Box',
    features: ['Precision FDM & Resin', 'Material variety', 'Digital proofing'],
  },
  {
    title: 'Medical & Dental Models',
    description: 'Detailed anatomical prints, clinic displays, and specialized medical tools.',
    icon: 'BriefcaseBusiness',
    features: ['High precision', 'Demonstration models', 'Custom scaling'],
  },
  {
    title: 'Home & Interior Decor',
    description: 'Modern vases, art sculptures, and customized organizers tailored to your space.',
    icon: 'Sparkles',
    features: ['Matte finish', 'Modern aesthetic', 'Durable materials'],
  },
  {
    title: 'Automotive Accessories',
    description: 'Bespoke car emblems, replacement clips, brackets, and dashboard accessories.',
    icon: 'Zap',
    features: ['Heat-resistant plastics', 'Perfect fitment', 'Custom badges'],
  },
];

export const testimonials: Testimonial[] = [
  {
    name: 'Nadia Rahman',
    role: 'Interior stylist',
    review: 'The home sculpture feels like it belongs in a gallery. Clean finish and incredible detail.',
    product: 'Minimalist Sculpture',
    avatar: 'NR',
    rating: 5,
  },
  {
    name: 'Dr. Karim T.',
    role: 'Clinic Director',
    review: 'The anatomical dental displays are super crisp and very helpful for patient explanations.',
    product: 'Anatomical Medical Model',
    avatar: 'KT',
    rating: 5,
  },
  {
    name: 'Sherif M.',
    role: 'Automotive Enthusiast',
    review: 'Had a custom car interior adapter printed. Perfect fitment and heat-resistant material.',
    product: 'Custom Vent Phone Mount',
    avatar: 'SM',
    rating: 5,
  },
];

export const faqs: FAQ[] = [
  {
    question: 'How long does 3D printing take?',
    answer: 'Standard in-stock models ship in 2–4 business days. Custom prototypes and scaled designs take 4–7 days depending on size and print hours.',
  },
  {
    question: 'What file formats do you accept for custom orders?',
    answer: 'We work primarily with STL, OBJ, and STEP files, but you can also submit standard CAD files, images, or dimensional sketches.',
  },
  {
    question: 'Can I request custom colors or finishes?',
    answer: 'Yes, we offer multiple colors and material options including PLA, PETG, ABS (for automotive use), and resin for ultra-fine details.',
  },
  {
    question: 'Do you deliver nationwide?',
    answer: 'Yes, nationwide shipping is available and calculated automatically during checkout.',
  },
];